package com.mycompany.masraflarwebapp.pojo;

// Generated Oct 5, 2012 2:18:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * Personel generated by hbm2java
 */
public class Personel implements java.io.Serializable {

	private Integer id;
	private String ad;
	private String soyad;
	private String cinsiyet;
	private String email;
	private String unvani;
	private int yetkiId;

	public Personel() {
	}

	public Personel(String ad, String soyad, String cinsiyet, String email,
			String unvani, int yetkiId) {
		this.ad = ad;
		this.soyad = soyad;
		this.cinsiyet = cinsiyet;
		this.email = email;
		this.unvani = unvani;
		this.yetkiId = yetkiId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public String getSoyad() {
		return this.soyad;
	}

	public void setSoyad(String soyad) {
		this.soyad = soyad;
	}

	public String getCinsiyet() {
		return this.cinsiyet;
	}

	public void setCinsiyet(String cinsiyet) {
		this.cinsiyet = cinsiyet;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUnvani() {
		return this.unvani;
	}

	public void setUnvani(String unvani) {
		this.unvani = unvani;
	}

	public int getYetkiId() {
		return this.yetkiId;
	}

	public void setYetkiId(int yetkiId) {
		this.yetkiId = yetkiId;
	}

}
