package com.mycompany.masraflarwebapp.pojo;

// Generated Oct 5, 2012 2:18:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * PersonelMasrafDetay generated by hbm2java
 */
public class PersonelMasrafDetay implements java.io.Serializable {

	private Integer id;
	private String fkRefMasrafKodu;
	private String tutar;
	private Integer fkPersonelMasrafId;

	public PersonelMasrafDetay() {
	}

	public PersonelMasrafDetay(String fkRefMasrafKodu) {
		this.fkRefMasrafKodu = fkRefMasrafKodu;
	}

	public PersonelMasrafDetay(String fkRefMasrafKodu, String tutar,
			Integer fkPersonelMasrafId) {
		this.fkRefMasrafKodu = fkRefMasrafKodu;
		this.tutar = tutar;
		this.fkPersonelMasrafId = fkPersonelMasrafId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFkRefMasrafKodu() {
		return this.fkRefMasrafKodu;
	}

	public void setFkRefMasrafKodu(String fkRefMasrafKodu) {
		this.fkRefMasrafKodu = fkRefMasrafKodu;
	}

	public String getTutar() {
		return this.tutar;
	}

	public void setTutar(String tutar) {
		this.tutar = tutar;
	}

	public Integer getFkPersonelMasrafId() {
		return this.fkPersonelMasrafId;
	}

	public void setFkPersonelMasrafId(Integer fkPersonelMasrafId) {
		this.fkPersonelMasrafId = fkPersonelMasrafId;
	}

}
