package com.mycompany.masraflarwebapp.pojo;

// Generated Oct 5, 2012 2:18:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PersonelMasraf generated by hbm2java
 */
public class PersonelMasraf implements java.io.Serializable {

	private Integer id;
	private String personelId;
	private Date masrafTarihi;
	private String masrafAciklama;
	private String araOnayliMi;
	private String tamOnayliMi;
	private Date araOnayTarihi;
	private Date tamOnayTarihi;

	public PersonelMasraf() {
	}

	public PersonelMasraf(Date masrafTarihi, String masrafAciklama) {
		this.masrafTarihi = masrafTarihi;
		this.masrafAciklama = masrafAciklama;
	}

	public PersonelMasraf(String personelId, Date masrafTarihi,
			String masrafAciklama, String araOnayliMi, String tamOnayliMi,
			Date araOnayTarihi, Date tamOnayTarihi) {
		this.personelId = personelId;
		this.masrafTarihi = masrafTarihi;
		this.masrafAciklama = masrafAciklama;
		this.araOnayliMi = araOnayliMi;
		this.tamOnayliMi = tamOnayliMi;
		this.araOnayTarihi = araOnayTarihi;
		this.tamOnayTarihi = tamOnayTarihi;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPersonelId() {
		return this.personelId;
	}

	public void setPersonelId(String personelId) {
		this.personelId = personelId;
	}

	public Date getMasrafTarihi() {
		return this.masrafTarihi;
	}

	public void setMasrafTarihi(Date masrafTarihi) {
		this.masrafTarihi = masrafTarihi;
	}

	public String getMasrafAciklama() {
		return this.masrafAciklama;
	}

	public void setMasrafAciklama(String masrafAciklama) {
		this.masrafAciklama = masrafAciklama;
	}

	public String getAraOnayliMi() {
		return this.araOnayliMi;
	}

	public void setAraOnayliMi(String araOnayliMi) {
		this.araOnayliMi = araOnayliMi;
	}

	public String getTamOnayliMi() {
		return this.tamOnayliMi;
	}

	public void setTamOnayliMi(String tamOnayliMi) {
		this.tamOnayliMi = tamOnayliMi;
	}

	public Date getAraOnayTarihi() {
		return this.araOnayTarihi;
	}

	public void setAraOnayTarihi(Date araOnayTarihi) {
		this.araOnayTarihi = araOnayTarihi;
	}

	public Date getTamOnayTarihi() {
		return this.tamOnayTarihi;
	}

	public void setTamOnayTarihi(Date tamOnayTarihi) {
		this.tamOnayTarihi = tamOnayTarihi;
	}

}
